[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
reqwest = { version = "0.12.4", features = ["stream", "rustls-tls"] }
oi_runner ={ path = "../oi_runner" }
log = { version = "0.4.21"}
pretty_env_logger = "0.5.0"
